---
- name: Deploy Health Care App
  hosts: all
  become: true
  tasks:

    - name: Ensure Jenkins workspace directory exists
      file:
        path: "/var/lib/jenkins/workspace/health_care"
        state: directory
        mode: '0755'

    - name: Copy Kubernetes Deployment file to Jenkins workspace
      copy:
        dest: "/var/lib/jenkins/workspace/health_care/health-deployment.yml"
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: health-app
            labels:
              app: health
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: health
            template:
              metadata:
                labels:
                  app: health
              spec:
                containers:
                - name: health
                  image: mohankumar12/health-care
                  ports:
                  - containerPort: 8082

    - name: Copy Kubernetes NodePort Service file to Jenkins workspace
      copy:
        dest: "/var/lib/jenkins/workspace/health_care/health-service.yml"
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: health-service
          spec:
            type: NodePort
            selector:
              app: health
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8082
                nodePort: 30080  # Ensure this is in the valid range (30000-32767)

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/health_care/health-deployment.yml --validate=false

    - name: Apply Kubernetes NodePort Service
      command: kubectl apply -f /var/lib/jenkins/workspace/health_care/health-service.yml --validate=false

    - name: Wait for pods to be in running state
      command: kubectl wait --for=condition=ready pod -l app=health --timeout=120s
      ignore_errors: yes

    - name: Display Service details
      command: kubectl get svc health-service -o wide
      register: service_output

    - name: Show Service output
      debug:
        var: service_output.stdout_lines
