---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
spec:
  selector:
    matchLabels:
      app: health-care
  replicas: 2
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
        - name: health-care
          image: mohankumar12/health-care  # Replace with your actual image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: health-care
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30091  # Ensure this is in the valid range (30000-32767)
  type: NodePort
